// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: http/v1/status.proto

package http

import (
	code "google.golang.org/genproto/googleapis/rpc/code"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This message defines the error schema for Google's JSON HTTP APIs.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The actual error payload. The nested message structure is for backward
	// compatibility with [Google API Client
	// Libraries](https://developers.google.com/api-client-library). It also
	// makes the error more readable to developers.
	Error         *Status `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_http_v1_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_http_v1_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_http_v1_status_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetError() *Status {
	if x != nil {
		return x.Error
	}
	return nil
}

// This message has the same semantics as `google.rpc.Status`. It uses HTTP
// status code instead of gRPC status code. It has extra fields `status` and
// `errors` for backward compatibility with [Google API Client
// Libraries](https://developers.google.com/api-client-library).
type Status struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The HTTP status code that corresponds to `google.rpc.Status.code`.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// This corresponds to `google.rpc.Status.message`.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// This is the enum version for `google.rpc.Status.code`.
	Status code.Code `protobuf:"varint,4,opt,name=status,proto3,enum=google.rpc.Code" json:"status,omitempty"`
	// This corresponds to `google.rpc.Status.details`.
	Details       []*anypb.Any `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_http_v1_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_http_v1_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_http_v1_status_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Status) GetStatus() code.Code {
	if x != nil {
		return x.Status
	}
	return code.Code(0)
}

func (x *Status) GetDetails() []*anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_http_v1_status_proto protoreflect.FileDescriptor

const file_http_v1_status_proto_rawDesc = "" +
	"\n" +
	"\x14http/v1/status.proto\x12\ahttp.v1\x1a\x19google/protobuf/any.proto\x1a\x15google/rpc/code.proto\".\n" +
	"\x05Error\x12%\n" +
	"\x05error\x18\x01 \x01(\v2\x0f.http.v1.StatusR\x05error\"\x90\x01\n" +
	"\x06Status\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x06status\x18\x04 \x01(\x0e2\x10.google.rpc.CodeR\x06status\x12.\n" +
	"\adetails\x18\x05 \x03(\v2\x14.google.protobuf.AnyR\adetailsBAZ?github.com/10664kls/automatic-finance-api/genproto/go/http;httpb\x06proto3"

var (
	file_http_v1_status_proto_rawDescOnce sync.Once
	file_http_v1_status_proto_rawDescData []byte
)

func file_http_v1_status_proto_rawDescGZIP() []byte {
	file_http_v1_status_proto_rawDescOnce.Do(func() {
		file_http_v1_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_http_v1_status_proto_rawDesc), len(file_http_v1_status_proto_rawDesc)))
	})
	return file_http_v1_status_proto_rawDescData
}

var file_http_v1_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_http_v1_status_proto_goTypes = []any{
	(*Error)(nil),     // 0: http.v1.Error
	(*Status)(nil),    // 1: http.v1.Status
	(code.Code)(0),    // 2: google.rpc.Code
	(*anypb.Any)(nil), // 3: google.protobuf.Any
}
var file_http_v1_status_proto_depIdxs = []int32{
	1, // 0: http.v1.Error.error:type_name -> http.v1.Status
	2, // 1: http.v1.Status.status:type_name -> google.rpc.Code
	3, // 2: http.v1.Status.details:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_http_v1_status_proto_init() }
func file_http_v1_status_proto_init() {
	if File_http_v1_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_v1_status_proto_rawDesc), len(file_http_v1_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_http_v1_status_proto_goTypes,
		DependencyIndexes: file_http_v1_status_proto_depIdxs,
		MessageInfos:      file_http_v1_status_proto_msgTypes,
	}.Build()
	File_http_v1_status_proto = out.File
	file_http_v1_status_proto_goTypes = nil
	file_http_v1_status_proto_depIdxs = nil
}
