CREATE TABLE "user" (
  id VARCHAR(12) NOT NULL PRIMARY KEY,
  username VARCHAR(200) NOT NULL UNIQUE,
  hash_password VARCHAR(200) NOT NULL,
  display_name VARCHAR(200) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'ENABLED' CHECK (status IN ('ENABLED', 'DISABLED', 'TERMINATED', 'LOCKED')),
  created_by VARCHAR(200) NOT NULL DEFAULT '',
  updated_by VARCHAR(200) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create index
CREATE INDEX idx_user_username ON "user" (username);
CREATE INDEX idx_created_at ON "user" (created_at);
CREATE INDEX idx_status ON "user" (status);


-- CREATE TABLE: role
CREATE TABLE role(
  id SERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(200) NOT NULL UNIQUE,
  display_name VARCHAR(200) NOT NULL,
  created_by VARCHAR(200) NOT NULL DEFAULT '',
  updated_by VARCHAR(200) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- CREATE TABLE: permission
CREATE TABLE permission(
  id SERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(200) NOT NULL UNIQUE,
  display_name VARCHAR(200) NOT NULL,
  created_by VARCHAR(200) NOT NULL DEFAULT '',
  updated_by VARCHAR(200) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CREATE TABLE: role_has_permission
CREATE TABLE role_has_permission(
  role_name VARCHAR(12) NOT NULL,
  permission_name VARCHAR(12) NOT NULL,
  created_by VARCHAR(200) NOT NULL DEFAULT '',
  updated_by VARCHAR(200) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (role_name, permission_name),
  FOREIGN KEY (role_name) REFERENCES role (name) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (permission_name) REFERENCES permission (name) ON DELETE CASCADE ON UPDATE CASCADE
);

-- CREATE TABLE: user_has_role
CREATE TABLE user_has_role(
  username VARCHAR(200) NOT NULL,
  role_name VARCHAR(12) NOT NULL,
  created_by VARCHAR(200) NOT NULL DEFAULT '',
  updated_by VARCHAR(200) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (username, role_name),
  FOREIGN KEY (username) REFERENCES "user" (username) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (role_name) REFERENCES role (name) ON DELETE CASCADE ON UPDATE CASCADE
);

-- CREATE INDEX
CREATE INDEX idx_user_has_role_username ON user_has_role(username);
